# Generated by Django 6.0.2 on 2026-05-02 02:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_initial'),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='courses.course'),
        ),
    ]
